<?php
// This code prevents page caching

	header("Cache-Control: no-cache, must-revalidate"); // HTTP/1.1			
	header("Expires: Sat, 26 Jul 1997 05:00:00 GMT"); 	// Date in the past	
	header("Pragma: no-cache");
?> 

<?php 
// "Database Connectivity"

	// Normally, because you only have to connect once per page,
	// you would put this at the top of the page.				

	
	// Server													
	$db_server = "localhost";
  
	// Database username (root is default)						
	$db_user = "root";
  
	// Database password 										
	// Our database doesn't have a password						
	$db_passwd = "";
  
	// Database name 											
	// In this example, should be the one you created in phase 1	
	$db_name = "productsdemo";
	
	// 1. Create a connection to the local database				
	$db_connected = mysqli_connect($db_server, $db_user, $db_passwd,$db_name) 
		or die("Not connected : " . mysql_error());

// End of "Database Connectivity"		
?>

<html>
 
<head>
	<title>Simple Scripting Demo</title>
</head>

<body />

<!-- ****************************************************************************************************************************************  --> 
<!-- FIRST STEP (1) *************************************************************************************************************************  --> 
<!-- ****************************************************************************************************************************************  --> 

<h2>Simple Scripting Demo</h2>
<br /><br />

<br /><br /><br />
<p><b><font color="#ff0000">Step 3 : The next ??? products are generated by scripting, bringing content in from the database ProductsDemo.
<br />Only certain records (Tools category) will be displayed!</font></b></p>




<?php

	
	$strSQL = "SELECT ID, Category, Image, Price, Description, Option2Desc, Option2a, Option2b, Option2c, Option2d, Option1Desc, Option1a, Option1b, Option1c, Option1d FROM Products";
        								
	$rsProd = mysqli_query($db_connected, $strSQL)
		or die($db_name . " : " . $strSQL . " : " . mysql_error());
		
// End Of "Retrieve Desired Record Set"
?>

<p><b>
<!-- Normally, we would not show this to the user! 									--> 
<!-- This is useful debug code so you can see what is going on behind the scenes 	-->
<font color="#ff0000">Connected to :: </font><?php echo $db_name; ?> <br />
<font color="#ff0000">Using SQL :: </font><?php echo $strSQL; ?> <br />
<font color="#ff0000">Records retrieved :: </font><?php echo mysqli_num_rows($rsProd); ?> <br /><br />
</b></p>

<?php 

  
  while ($rowProd = mysqli_fetch_array($rsProd)) {
  

	   
	   echo '
		  <hr /><br />
		  <img src="images/' 		. $rowProd["Image"] . '.gif" height=100 width=100 align=left />
		  Item #' 					. $rowProd["ID"] .  
		  '<br />Price :: ' 		. number_format($rowProd["Price"], 2, ".", ",") . 
		  '<br />Category :: ' 		. $rowProd["Category"] . 
		  '<br />Description :: '     . $rowProd["Description"]  . '   
		';
		
	
		
		Options($rowProd["Option1Desc"], $rowProd["Option1a"], $rowProd["Option1b"], $rowProd["Option1c"], $rowProd["Option1d"]);			
							
		Options($rowProd["Option2Desc"], $rowProd["Option2a"], $rowProd["Option2b"], $rowProd["Option2c"], $rowProd["Option2d"]);
                
                
} // End of the while		



function Options($OptionDesc, $OptionA, $OptionB, $OptionC, $OptionD){    
    if ($OptionDesc != "") {
			echo '
				<br clear=all /><br />' .
				$OptionDesc . '<br />
				<ul>';
                        if($OptionA != ""){
                            
                            echo '<li>' . $OptionA . '</li>';
                            
                            if($OptionB != ""){
                                    
                                echo '<li>' . $OptionB . '</li>';
                                    
                                if($OptionC != ""){
                                     
                                    echo '<li>' . $OptionC .'</li>';
                                    
                                    if($OptionD != ""){
                                        echo '<li>' . $OptionD . "</li>"
                                ;
                                        }//end of 1d
                                    }//end of option1c
                                }//end of option1b
			echo "</ul>";
                        }//end of option1a
                            
		}
}

?>
</BODY>
</HTML>